# Use an official Node.js runtime as a parent image
FROM node:18-alpine3.18

# Set the working directory
WORKDIR /usr/src/app
ENV NODE_ENV=production

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

RUN npx prisma generate

# Compile TypeScript
RUN npm run build

# Expose the port your app runs on
EXPOSE 8000

# Command to run your app
CMD ["node", "dist/index.js"]  # Adjust the path as per your output